folder: "../tick_data/data_aggrate/tick_bar"
start_date: "2024-01-01"
end_date: "2025-12-01"
file_format: "parquet"
#asset_list: ['SFPUSDT']
use_cache: true
use_mmap: False
file_end: "USDT"
parallel: true
