services:
  celery_worker:
    build:
      context: .
    container_name: celery_worker
    command: celery -A your_module_name worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
