DATA_PATH: data
LOG_PATH: log
MAX_ATTEMPT_TIMES: 5
ALLOW_MAX_MISSING_TIMESTAMPS: 20000
CSV_CHUNK_SIZE: 100000
GLOABLE_THREADS: 100
LOCAL_THREADS_RATIO: 5
DEFAULT_SINCE_TIME: 1262275200000
ENABLE_PROXY: true
SAVE_MISSING_TIMES: true
CONSOLE_LOG: true
FILE_LOG: true
GLOBAL_RATE_LIMIT: false